// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

// 指定所在包包名

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 定义枚举类型
type Week int32

const (
	// 枚举值必须从0开始
	Week_Monday  Week = 0
	Week_Tuesday Week = 1
)

var Week_name = map[int32]string{
	0: "Monday",
	1: "Tuesday",
}

var Week_value = map[string]int32{
	"Monday":  0,
	"Tuesday": 1,
}

func (x Week) String() string {
	return proto.EnumName(Week_name, int32(x))
}

func (Week) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

// 定义消息体
type Student struct {
	Age   int32   `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	P     *People `protobuf:"bytes,3,opt,name=p,proto3" json:"p,omitempty"`
	Score []int32 `protobuf:"varint,4,rep,packed,name=score,proto3" json:"score,omitempty"`
	// 枚举
	W Week `protobuf:"varint,5,opt,name=w,proto3,enum=04-protoc-pb.Week" json:"w,omitempty"`
	// 联合体
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Student_Teacher
	//	*Student_Class
	Data                 isStudent_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetP() *People {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *Student) GetScore() []int32 {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *Student) GetW() Week {
	if m != nil {
		return m.W
	}
	return Week_Monday
}

type isStudent_Data interface {
	isStudent_Data()
}

type Student_Teacher struct {
	Teacher string `protobuf:"bytes,6,opt,name=teacher,proto3,oneof"`
}

type Student_Class struct {
	Class string `protobuf:"bytes,7,opt,name=class,proto3,oneof"`
}

func (*Student_Teacher) isStudent_Data() {}

func (*Student_Class) isStudent_Data() {}

func (m *Student) GetData() isStudent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Student) GetTeacher() string {
	if x, ok := m.GetData().(*Student_Teacher); ok {
		return x.Teacher
	}
	return ""
}

func (m *Student) GetClass() string {
	if x, ok := m.GetData().(*Student_Class); ok {
		return x.Class
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Student) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Student_OneofMarshaler, _Student_OneofUnmarshaler, _Student_OneofSizer, []interface{}{
		(*Student_Teacher)(nil),
		(*Student_Class)(nil),
	}
}

func _Student_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Student)
	// data
	switch x := m.Data.(type) {
	case *Student_Teacher:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Teacher)
	case *Student_Class:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Class)
	case nil:
	default:
		return fmt.Errorf("Student.Data has unexpected type %T", x)
	}
	return nil
}

func _Student_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Student)
	switch tag {
	case 6: // data.teacher
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &Student_Teacher{x}
		return true, err
	case 7: // data.class
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &Student_Class{x}
		return true, err
	default:
		return false, nil
	}
}

func _Student_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Student)
	// data
	switch x := m.Data.(type) {
	case *Student_Teacher:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Teacher)))
		n += len(x.Teacher)
	case *Student_Class:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Class)))
		n += len(x.Class)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type People struct {
	Weight               int32    `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *People) Reset()         { *m = People{} }
func (m *People) String() string { return proto.CompactTextString(m) }
func (*People) ProtoMessage()    {}
func (*People) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *People) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_People.Unmarshal(m, b)
}
func (m *People) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_People.Marshal(b, m, deterministic)
}
func (m *People) XXX_Merge(src proto.Message) {
	xxx_messageInfo_People.Merge(m, src)
}
func (m *People) XXX_Size() int {
	return xxx_messageInfo_People.Size(m)
}
func (m *People) XXX_DiscardUnknown() {
	xxx_messageInfo_People.DiscardUnknown(m)
}

var xxx_messageInfo_People proto.InternalMessageInfo

func (m *People) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterEnum("04-protoc-pb.Week", Week_name, Week_value)
	proto.RegisterType((*Student)(nil), "04-protoc-pb.Student")
	proto.RegisterType((*People)(nil), "04-protoc-pb.People")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x3b, 0x4d, 0xb2, 0xb1, 0x13, 0x90, 0x32, 0x48, 0x58, 0x7a, 0xd0, 0xa5, 0x07, 0x09,
	0x1e, 0x72, 0x88, 0x6f, 0xe0, 0xc9, 0x8b, 0x20, 0x5b, 0xc1, 0xf3, 0x26, 0x19, 0x5a, 0xb1, 0x26,
	0x4b, 0x76, 0x4b, 0xe8, 0x73, 0xf9, 0x82, 0xb2, 0x4d, 0x84, 0xde, 0xfe, 0x6f, 0x66, 0x98, 0x7f,
	0xe6, 0xc7, 0xd5, 0x60, 0x9b, 0xd2, 0x0e, 0xbd, 0xef, 0x69, 0x69, 0xeb, 0xed, 0x2f, 0x60, 0xba,
	0xf3, 0xa7, 0x96, 0x3b, 0x4f, 0x6b, 0x8c, 0xcc, 0x9e, 0x25, 0x28, 0x28, 0x12, 0x1d, 0x24, 0x11,
	0xc6, 0x9d, 0xf9, 0x61, 0xb9, 0x54, 0x50, 0xac, 0xf4, 0x45, 0x93, 0x44, 0xb0, 0x32, 0x52, 0x50,
	0x64, 0x15, 0x96, 0xb6, 0x2e, 0xdf, 0xb9, 0xb7, 0x47, 0xd6, 0x60, 0xe9, 0x0e, 0x13, 0xd7, 0xf4,
	0x03, 0xcb, 0x58, 0x45, 0x45, 0xa2, 0x27, 0xa0, 0x1c, 0x61, 0x94, 0x89, 0x82, 0xe2, 0xb6, 0xba,
	0x09, 0xf3, 0x9f, 0xcc, 0xdf, 0x1a, 0x46, 0xda, 0x60, 0xea, 0xd9, 0x34, 0x07, 0x1e, 0xa4, 0x08,
	0xeb, 0x5f, 0x17, 0xfa, 0xbf, 0x40, 0x39, 0x26, 0xcd, 0xd1, 0x38, 0x27, 0xd3, 0xb9, 0x33, 0xe1,
	0x8b, 0xc0, 0xb8, 0x35, 0xde, 0x6c, 0x15, 0x8a, 0xc9, 0x96, 0x72, 0x14, 0x23, 0x7f, 0xed, 0x0f,
	0x7e, 0x3e, 0x7b, 0xa6, 0xa7, 0x07, 0x8c, 0x83, 0x11, 0x21, 0x8a, 0xb7, 0xbe, 0x6b, 0xcd, 0x79,
	0xbd, 0xa0, 0x0c, 0xd3, 0x8f, 0x13, 0xbb, 0x00, 0x50, 0x3d, 0x62, 0xec, 0xd9, 0x79, 0xba, 0xc7,
	0x68, 0x67, 0xce, 0x74, 0xf5, 0xca, 0x26, 0x0b, 0x7a, 0x0e, 0xa5, 0x16, 0x97, 0xac, 0x9e, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x4a, 0x3f, 0xc4, 0x38, 0x01, 0x00, 0x00,
}
